namespace MyanmarTools.Transliterate
{
    /// <summary>
    ///Transliteration initialization of Phases and rules.
    /// Note: this is generated by compiling ICU transliteration rule format.
    /// Source rule file = genconvert/input/my-t-my-d0-zawgyi.txt
    /// </summary>
    public class TransliterateU2Z : Transliterate
    {
        public TransliterateU2Z(string name) : base(name)
        {

            // Rules for Phase 0
            var Phase0 = AddPhase();
            Phase0.AddRule(new Rule("[\u1004\u101B\u105A]\u103A\u1039([\u1000-\u1021])\u103B", "$1\u103A\u1064"));
            Phase0.AddRule(new Rule("[\u1004\u101B\u105A]\u103A\u1039([\u1000-\u1021])\u102D\u1036", "$1\u108E"));
            Phase0.AddRule(new Rule("[\u1004\u101B\u105A]\u103A\u1039([\u1000-\u1021])\u102D", "$1\u108B"));
            Phase0.AddRule(new Rule("[\u1004\u101B\u105A]\u103A\u1039([\u1000-\u1021])\u102E", "$1\u108C"));
            Phase0.AddRule(new Rule("[\u1004\u101B\u105A]\u103A\u1039([\u1000-\u1021])\u1036", "$1\u108D"));
            Phase0.AddRule(new Rule("[\u1004\u101B\u105A]\u103A\u1039([\u1000-\u1021])\u1031", "$1\u1031\u1064"));
            Phase0.AddRule(new Rule("[\u1004\u101B\u105A]\u103A\u1039([\u1000-\u1021])\u103B\u102D\u102F", "$1\u103A\u1033\u108B"));
            Phase0.AddRule(new Rule("[\u1004\u101B\u105A]\u103A\u1039([\u1000-\u1021])\u103B\u102D", "$1\u103A\u108B"));
            Phase0.AddRule(new Rule("[\u1004\u101B\u105A]\u103A\u1039([\u1000-\u1021])\u103B\u102E\u102F", "$1\u103A\u108C\u1033"));
            Phase0.AddRule(new Rule("[\u1004\u101B\u105A]\u103A\u1039([\u1000-\u1021])\u103B\u102E", "$1\u103A\u108C"));
            Phase0.AddRule(new Rule("[\u1004\u101B\u105A]\u103A\u1039([\u1000-\u1021])\u103B\u1036", "$1\u103A\u108D"));
            Phase0.AddRule(new Rule("[\u1004\u101B\u105A]\u103A\u1039([\u1000-\u1021])\u103C", "$1\u103B\u1064"));
            Phase0.AddRule(new Rule("[\u1004\u101B\u105A]\u103A\u1039\u102D", "\u108B"));
            Phase0.AddRule(new Rule("[\u1004\u101B\u105A]\u103A\u1039\u102E", "\u108C"));
            Phase0.AddRule(new Rule("[\u1004\u101B\u105A]\u103A\u1039\u1036", "\u108D"));
            Phase0.AddRule(new Rule("[\u1004\u101B\u105A]\u103A\u1039([\u1000-\u1021])", "$1\u1064"));
            Phase0.AddRule(new Rule("\u1025([\u102B-\u1030\u1032])\u1038", "\u106A$1\u1038"));
            Phase0.AddRule(new Rule("\u1025\u102F\u1036", "\u1025\u1036\u1033"));
            Phase0.AddRule(new Rule("\u102D\u1036", "\u108E"));
            Phase0.AddRule(new Rule("\u103D\u103E", "\u108A"));
            Phase0.AddRule(new Rule("\u103E\u102F", "\u1088"));
            Phase0.AddRule(new Rule("\u103E\u1030", "\u1089"));
            Phase0.AddRule(new Rule("\u103A", "\u1039"));
            Phase0.AddRule(new Rule("\u103B", "\u103A"));
            Phase0.AddRule(new Rule("\u103C", "\u103B"));
            Phase0.AddRule(new Rule("\u103D", "\u103C"));
            Phase0.AddRule(new Rule("\u103E", "\u103D"));
            Phase0.AddRule(new Rule("\u103F", "\u1086"));
            Phase0.AddRule(new Rule("([\u1019])\u103E\u1030", "$1\u103D\u1034"));
            Phase0.AddRule(new Rule("\u102B\u103A", "\u105A"));
            Phase0.AddRule(new Rule("\u1039\u1010\u103D", "\u1096"));
            Phase0.AddRule(new Rule("\u1039\u1000", "\u1060"));
            Phase0.AddRule(new Rule("\u1039\u1001", "\u1061"));
            Phase0.AddRule(new Rule("\u1039\u1002", "\u1062"));
            Phase0.AddRule(new Rule("\u1039\u1003", "\u1063"));
            Phase0.AddRule(new Rule("\u1039\u1005", "\u1065"));
            Phase0.AddRule(new Rule("\u1039\u1006", "\u1067"));
            Phase0.AddRule(new Rule("\u1039\u1007", "\u1068"));
            Phase0.AddRule(new Rule("\u1039\u1008", "\u1069"));
            Phase0.AddRule(new Rule("\u1039\u100B", "\u106C"));
            Phase0.AddRule(new Rule("\u1039\u100C", "\u106D"));
            Phase0.AddRule(new Rule("\u1039\u100F", "\u1070"));
            Phase0.AddRule(new Rule("\u1039\u1010", "\u1072"));
            Phase0.AddRule(new Rule("\u1039\u1011", "\u1074"));
            Phase0.AddRule(new Rule("\u1039\u1012", "\u1075"));
            Phase0.AddRule(new Rule("\u1039\u1013", "\u1076"));
            Phase0.AddRule(new Rule("\u1039\u1014", "\u1077"));
            Phase0.AddRule(new Rule("\u1039\u1015", "\u1078"));
            Phase0.AddRule(new Rule("\u1039\u1016", "\u1079"));
            Phase0.AddRule(new Rule("\u1039\u1017", "\u107A"));
            Phase0.AddRule(new Rule("\u1039\u1018", "\u1093"));
            Phase0.AddRule(new Rule("\u1039\u1019", "\u107C"));
            Phase0.AddRule(new Rule("\u1039\u101C", "\u1085"));
            Phase0.AddRule(new Rule("\u100D\u1039\u100D", "\u106E"));
            Phase0.AddRule(new Rule("\u100D\u1039\u100E", "\u106F"));
            Phase0.AddRule(new Rule("\u100F\u1039\u100D", "\u1091"));
            Phase0.AddRule(new Rule("\u100B\u1039\u100C", "\u1092"));
            Phase0.AddRule(new Rule("\u100B\u1039\u100B", "\u1097"));
            Phase0.AddRule(new Rule("\u104E\u1004\u103A\u1038", "\u104E"));

            // Rules for Phase 1
            var Phase1 = AddPhase();
            Phase1.AddRule(new Rule("\u1014([\u1060-\u1068\u106C\u106D\u1070-\u107C\u1085\u1093\u1096])([\u102D\u102E\u1032\u1036\u1039\u1064]*)\u103B", "\u103B\u108F$1$2"));
            Phase1.AddRule(new Rule("\u1014\u103B([\u103C\u103D]*)(\u1031*)", "$2\u103B\u108F$1"));
            Phase1.AddRule(new Rule("([\u1000-\u1021])\u103B([\u103C\u103D]*)\u1031", "\u1031\u103B$1$2"));
            Phase1.AddRule(new Rule("([\u1000-\u1021])\u103B", "\u103B$1"));
            Phase1.AddRule(new Rule("([\u1000-\u1021])\u103D\u1031\u1037", "\u1031$1\u1094\u103D"));
            Phase1.AddRule(new Rule("([\u1000-\u1021])(\u108A)\u1031", "\u1031$1$2"));
            Phase1.AddRule(new Rule("([\u1000-\u1021])\u1064\u103B", "\u103B$1\u1064"));
            Phase1.AddRule(new Rule("([\u1000-\u1021])([\u103A\u103C\u103D]+)\u1031", "\u1031$1$2"));
            Phase1.AddRule(new Rule("([\u1000-\u1021])([\u1060-\u1068\u106C\u106D\u1070-\u107C\u1085\u1093\u1096])([\u102D\u102E\u1032\u1036\u1039\u1064]*)\u103B", "\u103B$1$2$3"));
            Phase1.AddRule(new Rule("([\u1000-\u102A])\u1031", "\u1031$1"));
            Phase1.AddRule(new Rule("\u1014([\u1060-\u1068\u106C\u106D\u1070-\u107C\u1085\u1093\u1096])", "\u108F$1"));
            Phase1.AddRule(new Rule("\u1014([\u102F\u1030\u1037\u103C\u103D\u1087-\u108A])([\u102D\u102E\u1032\u1036\u1039\u1064])\u1037", "\u108F$1$2\u1094"));
            Phase1.AddRule(new Rule("\u1014([\u102D\u102E\u1032\u1036\u1039\u1064])([\u102F\u1030\u1037\u103C\u103D\u1087-\u108A])\u1037", "\u108F$1$2\u1094"));
            Phase1.AddRule(new Rule("\u1014([\u102D\u102E\u1032\u1036\u1039\u1064])\u1037", "\u1014$1\u1094"));
            Phase1.AddRule(new Rule("\u1014\u1032\u1037", "\u1014\u1032\u1094"));
            Phase1.AddRule(new Rule("\u1014\u1037", "\u1014\u1094"));
            Phase1.AddRule(new Rule("\u1014\u1032([\u102F\u1030\u1037\u103C\u103D\u1087-\u108A])\u1037", "\u108F$1\u1032\u1094"));
            Phase1.AddRule(new Rule("\u1014([\u102D\u102E\u1032\u1036\u1039\u1064])([\u102F\u1030\u1037\u103C\u103D\u1087-\u108A])", "\u108F$1$2"));
            Phase1.AddRule(new Rule("\u1014([\u102F\u1030\u1037\u103C\u103D\u1087-\u108A])([\u102D\u102E\u1032\u1036\u1039\u1064])", "\u108F$1$2"));
            Phase1.AddRule(new Rule("\u1014([\u102F\u1030\u1037\u103C\u103D\u1087-\u108A])\u1037", "\u108F$1\u1094"));
            Phase1.AddRule(new Rule("\u1014([\u102F\u1030\u1037\u103C\u103D\u1087-\u108A])", "\u108F$1"));
            Phase1.AddRule(new Rule("([\u102F\u1030\u1037\u103C\u103D\u1087-\u108A])([\u102D\u102E\u1032\u1036\u1039\u1064]*)\u1037", "$1$2\u1094"));
            Phase1.AddRule(new Rule("([^\u1040-\u1049])\u1040([\u102B-\u103F])", "$1\u101D$2"));
            Phase1.AddRule(new Rule("([^\u1040-\u1049])\u104E", "$1\u1044"));
            Phase1.AddRule(new Rule("\u1031\u1040([^\u1040-\u1049])", "\u1031\u101D$1"));
            Phase1.AddRule(new Rule("\u1009\u103A", "\u1025\u103A"));
            Phase1.AddRule(new Rule("\u1025\u102E", "\u1026"));
            Phase1.AddRule(new Rule("\u1037\u103A", "\u103A\u1037"));
            Phase1.AddRule(new Rule("([\u102B\u102C\u102F\u1030])([\u102D\u102E\u1032])", "$2$1"));

            // Rules for Phase 2
            var Phase2 = AddPhase();
            Phase2.AddRule(new Rule("\u103A\u103C", "\u103C\u107D"));
            Phase2.AddRule(new Rule("\u103C\u1094", "\u103C\u1095"));
            Phase2.AddRule(new Rule("[\u103B\u107E-\u1084]([\u1001\u1002\u1004\u1005\u1007\u100B-\u100E\u1012\u1013\u1015-\u1017\u1019\u101D\u1020\u1025\u1026\u108F])([\u1060-\u1068\u106C\u106D\u1070-\u107C\u1085\u1093\u1096])([\u102D\u102E\u1032\u1036\u1039\u1064])", "\u1083$1$2$3"));
            Phase2.AddRule(new Rule("[\u103B\u107E-\u1084]([\u1000\u1003\u1006\u1009\u100A\u100F-\u1011\u1018\u101C\u101E\u101F\u1021])([\u1060-\u1068\u106C\u106D\u1070-\u107C\u1085\u1093\u1096])([\u102D\u102E\u1032\u1036\u1039\u1064])", "\u1084$1$2$3"));
            Phase2.AddRule(new Rule("[\u103B\u107E-\u1084]([\u1001\u1002\u1004\u1005\u1007\u100B-\u100E\u1012\u1013\u1015-\u1017\u1019\u101D\u1020\u1025\u1026\u108F])([\u1060-\u1068\u106C\u106D\u1070-\u107C\u1085\u1093\u1096])", "\u1081$1$2"));
            Phase2.AddRule(new Rule("[\u103B\u107E-\u1084]([\u1000\u1003\u1006\u1009\u100A\u100F-\u1011\u1018\u101C\u101E\u101F\u1021])([\u1060-\u1068\u106C\u106D\u1070-\u107C\u1085\u1093\u1096])", "\u1082$1$2"));
            Phase2.AddRule(new Rule("[\u103B\u107E-\u1084]([\u1001\u1002\u1004\u1005\u1007\u100B-\u100E\u1012\u1013\u1015-\u1017\u1019\u101D\u1020\u1025\u1026\u108F])([\u103C\u108A])([\u102D\u102E\u1032\u1036\u1039\u1064])", "\u1083$1$2$3"));
            Phase2.AddRule(new Rule("[\u103B\u107E-\u1084]([\u1000\u1003\u1006\u1009\u100A\u100F-\u1011\u1018\u101C\u101E\u101F\u1021])([\u103C\u108A])([\u102D\u102E\u1032\u1036\u1039\u1064])", "\u1084$1$2$3"));
            Phase2.AddRule(new Rule("[\u103B\u107E-\u1084]([\u1001\u1002\u1004\u1005\u1007\u100B-\u100E\u1012\u1013\u1015-\u1017\u1019\u101D\u1020\u1025\u1026\u108F])\u103D([\u102D\u102E\u1032\u1036\u1039\u1064])", "\u107F$1\u1087$2"));
            Phase2.AddRule(new Rule("[\u103B\u107E-\u1084]([\u1000\u1003\u1006\u1009\u100A\u100F-\u1011\u1018\u101C\u101E\u101F\u1021])\u103D([\u102D\u102E\u1032\u1036\u1039\u1064])", "\u1080$1\u1087$2"));
            Phase2.AddRule(new Rule("[\u103B\u107E-\u1084]([\u1001\u1002\u1004\u1005\u1007\u100B-\u100E\u1012\u1013\u1015-\u1017\u1019\u101D\u1020\u1025\u1026\u108F])\u102F([\u102D\u102E\u1032\u1036\u1039\u1064])", "\u107F$1\u1033$2"));
            Phase2.AddRule(new Rule("[\u103B\u107E-\u1084]([\u1000\u1003\u1006\u1009\u100A\u100F-\u1011\u1018\u101C\u101E\u101F\u1021])\u102F([\u102D\u102E\u1032\u1036\u1039\u1064])", "\u1080$1\u1033$2"));
            Phase2.AddRule(new Rule("[\u103B\u107E-\u1084]([\u1001\u1002\u1004\u1005\u1007\u100B-\u100E\u1012\u1013\u1015-\u1017\u1019\u101D\u1020\u1025\u1026\u108F])\u1030([\u102D\u102E\u1032\u1036\u1039\u1064])", "\u107F$1\u1034$2"));
            Phase2.AddRule(new Rule("[\u103B\u107E-\u1084]([\u1000\u1003\u1006\u1009\u100A\u100F-\u1011\u1018\u101C\u101E\u101F\u1021])\u1030([\u102D\u102E\u1032\u1036\u1039\u1064])", "\u1080$1\u1034$2"));
            Phase2.AddRule(new Rule("[\u103B\u107E-\u1084]([\u1001\u1002\u1004\u1005\u1007\u100B-\u100E\u1012\u1013\u1015-\u1017\u1019\u101D\u1020\u1025\u1026\u108F])([\u102F\u1030\u1037\u103C\u103D\u1087-\u108A]*)([\u102D\u102E\u1032\u1036\u1039\u1064])", "\u107F$1$2$3"));
            Phase2.AddRule(new Rule("[\u103B\u107E-\u1084]([\u1000\u1003\u1006\u1009\u100A\u100F-\u1011\u1018\u101C\u101E\u101F\u1021])([\u102F\u1030\u1037\u103C\u103D\u1087-\u108A]*)([\u102D\u102E\u1032\u1036\u1039\u1064])", "\u1080$1$2$3"));
            Phase2.AddRule(new Rule("[\u103B\u107E-\u1084]([\u1001\u1002\u1004\u1005\u1007\u100B-\u100E\u1012\u1013\u1015-\u1017\u1019\u101D\u1020\u1025\u1026\u108F])([\u103C\u108A])", "\u1081$1$2"));
            Phase2.AddRule(new Rule("[\u103B\u107E-\u1084]([\u1000\u1003\u1006\u1009\u100A\u100F-\u1011\u1018\u101C\u101E\u101F\u1021])([\u103C\u108A])", "\u1082$1$2"));
            Phase2.AddRule(new Rule("[\u103B\u107E-\u1084]([\u1001\u1002\u1004\u1005\u1007\u100B-\u100E\u1012\u1013\u1015-\u1017\u1019\u101D\u1020\u1025\u1026\u108F])\u103D", "\u103B$1\u1087"));
            Phase2.AddRule(new Rule("[\u103B\u107E-\u1084]([\u1000\u1003\u1006\u1009\u100A\u100F-\u1011\u1018\u101C\u101E\u101F\u1021])\u103D", "\u107E$1\u1087"));
            Phase2.AddRule(new Rule("[\u103B\u107E-\u1084]([\u1001\u1002\u1004\u1005\u1007\u100B-\u100E\u1012\u1013\u1015-\u1017\u1019\u101D\u1020\u1025\u1026\u108F])\u102F", "\u103B$1\u1033"));
            Phase2.AddRule(new Rule("[\u103B\u107E-\u1084]([\u1000\u1003\u1006\u1009\u100A\u100F-\u1011\u1018\u101C\u101E\u101F\u1021])\u102F", "\u107E$1\u1033"));
            Phase2.AddRule(new Rule("[\u103B\u107E-\u1084]([\u1001\u1002\u1004\u1005\u1007\u100B-\u100E\u1012\u1013\u1015-\u1017\u1019\u101D\u1020\u1025\u1026\u108F])\u1030", "\u103B$1\u1034"));
            Phase2.AddRule(new Rule("[\u103B\u107E-\u1084]([\u1000\u1003\u1006\u1009\u100A\u100F-\u1011\u1018\u101C\u101E\u101F\u1021])\u1030", "\u107E$1\u1034"));
            Phase2.AddRule(new Rule("[\u103B\u107E-\u1084]([\u100A\u106B])", "\u1082$1"));
            Phase2.AddRule(new Rule("[\u103B\u107E-\u1084]([\u1009\u106A])", "\u103B\u106A"));
            Phase2.AddRule(new Rule("[\u103B\u107E-\u1084]([\u1001\u1002\u1004\u1005\u1007\u100B-\u100E\u1012\u1013\u1015-\u1017\u1019\u101D\u1020\u1025\u1026\u108F])", "\u103B$1"));
            Phase2.AddRule(new Rule("[\u103B\u107E-\u1084]([\u1000\u1003\u1006\u1009\u100A\u100F-\u1011\u1018\u101C\u101E\u101F\u1021])", "\u107E$1"));
            Phase2.AddRule(new Rule("\u1009([\u102F\u1030\u1037\u103C\u103D\u1087-\u108A])", "\u106A$1"));
            Phase2.AddRule(new Rule("\u100A([\u102F\u1030\u1037\u103C\u103D\u1087-\u108A])", "\u106B$1"));
            Phase2.AddRule(new Rule("\u103D\u102D", "\u102D\u103D"));
            Phase2.AddRule(new Rule("\u103A([\u102D\u102E\u1032\u1036\u1039\u1064])\u102F[\u1037\u1094\u1095]", "\u103A$1\u1033\u1095"));
            Phase2.AddRule(new Rule("\u103A\u102F[\u1037\u1094\u1095]", "\u103A\u1033\u1095"));
            Phase2.AddRule(new Rule("\u103A\u102F", "\u103A\u1033"));
            Phase2.AddRule(new Rule("\u1064\u102E", "\u108C"));

            // Rules for Phase 3
            var Phase3 = AddPhase();
            Phase3.AddRule(new Rule("\u1037([\u102D-\u1030\u1032\u1036])", "$1\u1037"));
            Phase3.AddRule(new Rule("([\u1000-\u1021])([\u102B-\u1032\u1036\u103B-\u103E])\u103A([\u1000-\u1021])", "$1\u103A$2$3"));
            Phase3.AddRule(new Rule("\u103D\u102F", "\u1088"));
            Phase3.AddRule(new Rule("\u1033\u1094", "\u1033\u1095"));
            Phase3.AddRule(new Rule("([\u103B\u107E-\u1084])([\u1001\u1002\u1004\u1005\u1007\u100B-\u100E\u1012\u1013\u1015-\u1017\u1019\u101D\u1020\u1025\u1026\u108F])([\u102F\u1030\u1037\u103C\u103D\u1087-\u108A]*)([\u102D\u102E\u1032\u1036\u1039\u1064]*)\u102F", "$1$2$3$4\u1033"));
            Phase3.AddRule(new Rule("([\u103B\u107E-\u1084])([\u1000\u1003\u1006\u1009\u100A\u100F-\u1011\u1018\u101C\u101E\u101F\u1021])([\u102F\u1030\u1037\u103C\u103D\u1087-\u108A]*)([\u102D\u102E\u1032\u1036\u1039\u1064]*)\u102F", "$1$2$3$4\u1033"));
            Phase3.AddRule(new Rule("([\u103B\u107E-\u1084])([\u1001\u1002\u1004\u1005\u1007\u100B-\u100E\u1012\u1013\u1015-\u1017\u1019\u101D\u1020\u1025\u1026\u108F])([\u102F\u1030\u1037\u103C\u103D\u1087-\u108A]*)([\u102D\u102E\u1032\u1036\u1039\u1064]*)\u1030", "$1$2$3$4\u1034"));
            Phase3.AddRule(new Rule("([\u103B\u107E-\u1084])([\u1000\u1003\u1006\u1009\u100A\u100F-\u1011\u1018\u101C\u101E\u101F\u1021])([\u102F\u1030\u1037\u103C\u103D\u1087-\u108A]*)([\u102D\u102E\u1032\u1036\u1039\u1064]*)\u1030", "$1$2$3$4\u1034"));

            // Rules for Phase 4
            var Phase4 = AddPhase();
            Phase4.AddRule(new Rule("([\u103D\u103E])\u103C", "\u103C$1"));
            Phase4.AddRule(new Rule("\u103E\u103D", "\u103D\u103E"));
            Phase4.AddRule(new Rule("\u1038([\u102B-\u1030\u1032\u103C-\u103F])", "$1\u1038"));
            Phase4.AddRule(new Rule("\u1038([\u1036\u1037\u103A])", "$1\u1038"));
            Phase4.AddRule(new Rule("\u103A([\u1064\u108B-\u108E])\u102D\u102F", "\u103A$1\u102D\u1033"));
            Phase4.AddRule(new Rule("\u103A\u102D\u102F", "\u103A\u102D\u1033"));

            // Rules for Phase 5
            var Phase5 = AddPhase();
            Phase5.AddRule(new Rule("([\u1000-\u1021])\u103B\u103A", "$1\u103A\u103B"));
            Phase5.AddRule(new Rule("([\u103C-\u103E])\u103B", "\u103B$1"));
            Phase5.AddRule(new Rule("([\u103D\u103E])\u103C", "\u103C$1"));
            Phase5.AddRule(new Rule("\u103E\u103D", "\u103D\u103E"));
            Phase5.AddRule(new Rule("([\u102D-\u1030\u1032])\u103A([\u1000-\u1021])\u103A", "$1$2\u103A"));
            Phase5.AddRule(new Rule("\u102D\u103A", "\u102D"));
            Phase5.AddRule(new Rule("\u102E\u103A", "\u102E"));
            Phase5.AddRule(new Rule("\u102F\u103A", "\u102F"));
            Phase5.AddRule(new Rule("\u102D\u102E", "\u102E"));
            Phase5.AddRule(new Rule("\u102F\u1030", "\u102F"));
            Phase5.AddRule(new Rule("\u102B\u102B+", "\u102B"));
            Phase5.AddRule(new Rule("\u102C\u102C+", "\u102C"));
            Phase5.AddRule(new Rule("\u102D\u102D+", "\u102D"));
            Phase5.AddRule(new Rule("\u102E\u102E+", "\u102E"));
            Phase5.AddRule(new Rule("\u102F\u102F+", "\u102F"));
            Phase5.AddRule(new Rule("\u1030\u1030+", "\u1030"));
            Phase5.AddRule(new Rule("\u1031\u1031+", "\u1031"));
            Phase5.AddRule(new Rule("\u1032\u1032+", "\u1032"));
            Phase5.AddRule(new Rule("\u1036\u1036+", "\u1036"));
            Phase5.AddRule(new Rule("\u103A\u103A+", "\u103A"));
            Phase5.AddRule(new Rule("\u103B\u103B+", "\u103B"));
            Phase5.AddRule(new Rule("\u103C\u103C+", "\u103C"));
            Phase5.AddRule(new Rule("\u103D\u103D+", "\u103D"));
            Phase5.AddRule(new Rule("\u103E\u103E+", "\u103E"));
            Phase5.AddRule(new Rule("([\u102F\u1033])\u102D", "\u102D$1"));
            Phase5.AddRule(new Rule("([\u102F\u1033])\u1036", "\u1036$1"));
            Phase5.AddRule(new Rule("\u1037\u1039", "\u1039\u1037"));
            Phase5.AddRule(new Rule("\u1032\u103C", "\u103C\u1032"));
            Phase5.AddRule(new Rule("\u102E\u103C", "\u103C\u102E"));
            Phase5.AddRule(new Rule("\u103D\u1088", "\u1088"));
        }

    }
}